# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# update with 'bundle update github-pages'
# run with 'bundle exec jekyll serve'

title: Dominic's Corner
#email: your-email@example.com
description: Some writing and some gaming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dominicsimone.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: dominicsimone

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# --- Collections ---
collections:
  games: # Name of the collection
    output: true # Generate individual pages for each game (e.g., /games/cool-blaster/)
    permalink: /games/:title/ # URL structure for individual game pages
    sort_by: date # Default sort order for the collection (add 'date' to game front matter)

# --- Defaults ---
# Set default layouts for posts and games
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "games" # Matches the collection name
    values:
      layout: "game" # Use 'game' layout for individual game pages
      # You could add other default game metadata here if desired
  - scope:
      path: "" # All other top-level pages
      type: "pages"
    values:
      layout: "page"

# --- Exclude from processing ---
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE